# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('permit_id', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('contacter', models.CharField(max_length=20)),
                ('permit_img', models.FileField(upload_to=b'permitImg')),
                ('bank_name', models.CharField(max_length=90)),
                ('money_amount', models.IntegerField(default=0)),
                ('account_bank_name', models.CharField(max_length=200)),
                ('bank_permit_img', models.FileField(upload_to=b'BankImg')),
                ('company_telphone', models.CharField(max_length=16)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('bussiness_area', models.CharField(choices=[(b'CS', b'computer science'), (b'EE', b'electric engnieer')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
