# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('is_varified', models.BooleanField(default=False)),
                ('reason_of_deny', models.TextField(blank=True, max_length=300, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.PositiveIntegerField()),
                ('major_area', models.CharField(choices=[(b'CS', b'computer science'), (b'EE', b'electric engnieer')], max_length=2)),
                ('state', models.CharField(choices=[(b'BJ', b'BJ'), (b'TJ', b'TJ')], max_length=2)),
                ('city', models.CharField(choices=[(b'HD', b'HD'), (b'BH', b'BH')], max_length=2)),
                ('department', models.ForeignKey(help_text=b'your department', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'recruitment_infos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
