# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_model', '0002_recruitmentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentinformation',
            name='department',
            field=models.ForeignKey(help_text=b'your department', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'post_infos'),
        ),
    ]
