# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_model', '0003_auto_20160809_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentinformation',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
