# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_model', '0004_recruitmentinformation_is_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentinformation',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
