# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='complain_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
