# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('major', models.CharField(choices=[(b'CS', b'computer science'), (b'EE', b'electric engnieer')], max_length=5)),
                ('degree', models.CharField(choices=[(b'H', b'Highschool'), (b'B', b'Banchler'), (b'M', b'Master'), (b'P', b'PHD')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
